// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlgwebfonhkywqhgniux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZ3dlYmZvbmhreXdxaGduaXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNzA1MDcsImV4cCI6MjA5MTg0NjUwN30.yqWRCYUU8wulloZYhBBByjt4qPASW4h9cI2VkxGtxxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});